# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_usu', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('amaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('ci', models.IntegerField()),
                ('fechaReg', models.DateField(blank=True, null=True)),
                ('bcontrol', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreS', models.CharField(max_length=100)),
                ('numeroS', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.Secretaria'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.Unidad'),
        ),
    ]
