# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0002_saldostotales'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionSecre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('identificacion', models.IntegerField()),
                ('valido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OtrosViajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_viaticos', models.SlugField(blank=True, null=True)),
                ('fecha_inicial_frontera', models.DateField(blank=True, null=True)),
                ('fecha_llegada_frontera', models.DateField(blank=True, null=True)),
                ('horaSalida_frontera', models.TimeField(blank=True, null=True)),
                ('horallegada_frontera', models.TimeField(blank=True, null=True)),
                ('lugar_frontera', models.CharField(blank=True, max_length=70, null=True)),
                ('fechav_frontera', models.CharField(blank=True, max_length=40, null=True)),
                ('calculohora_frontera', models.CharField(blank=True, max_length=40, null=True)),
                ('dias_frontera', models.FloatField(blank=True, null=True)),
                ('fecha_inicial_urbana', models.DateField(blank=True, null=True)),
                ('fecha_llegada_urbana', models.DateField(blank=True, null=True)),
                ('horaSalida_urbana', models.TimeField(blank=True, null=True)),
                ('horallegada_urbana', models.TimeField(blank=True, null=True)),
                ('lugar_urbana', models.CharField(blank=True, max_length=70, null=True)),
                ('fechav_urbana', models.CharField(blank=True, max_length=40, null=True)),
                ('calculohora_urbana', models.CharField(blank=True, max_length=40, null=True)),
                ('dias_urbana', models.FloatField(blank=True, null=True)),
                ('fecha_inicial_rural', models.DateField(blank=True, null=True)),
                ('fecha_llegada_rural', models.DateField(blank=True, null=True)),
                ('horaSalida_rural', models.TimeField(blank=True, null=True)),
                ('horallegada_rural', models.TimeField(blank=True, null=True)),
                ('lugar_rural', models.CharField(blank=True, max_length=70, null=True)),
                ('fechav_rural', models.CharField(blank=True, max_length=40, null=True)),
                ('calculohora_rural', models.CharField(blank=True, max_length=40, null=True)),
                ('dias_rural', models.FloatField(blank=True, null=True)),
                ('tipos_viajante', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecresubSecre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue', models.IntegerField()),
                ('prog', models.IntegerField()),
                ('proy', models.IntegerField()),
                ('act', models.IntegerField()),
                ('gestion', models.IntegerField()),
                ('descripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.DescripcionSecre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_viatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Viajante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='viaticodiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_u', models.IntegerField()),
                ('id_solicitante', models.IntegerField(blank=True, null=True)),
                ('Monto_pagado', models.FloatField()),
                ('RC_IVA', models.FloatField()),
                ('Liquido_pagable', models.FloatField()),
                ('pasaje', models.FloatField(blank=True, default=0, null=True)),
                ('peaje', models.FloatField(blank=True, default=0, null=True)),
                ('Extra', models.FloatField(blank=True, default=0, null=True)),
                ('totalC', models.FloatField()),
                ('cantidad_dias_fuera_pais', models.IntegerField(blank=True, null=True)),
                ('resolucion', models.NullBooleanField(default=False)),
                ('cambio_moneda', models.FloatField(blank=True, null=True)),
                ('ue', models.IntegerField()),
                ('prog', models.IntegerField()),
                ('act', models.IntegerField()),
                ('proy', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_legada', models.DateField(blank=True, null=True)),
                ('horaSalida', models.TimeField(blank=True, null=True)),
                ('horallegada', models.TimeField(blank=True, null=True)),
                ('fechav', models.CharField(max_length=40)),
                ('calculohora', models.CharField(blank=True, max_length=40, null=True)),
                ('dias', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('encargado', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=70)),
                ('ncontrol', models.IntegerField()),
                ('estado', models.CharField(blank=True, default=1, max_length=10, null=True)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('centralizador', models.IntegerField(blank=True, default=0, null=True)),
                ('monto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.Monto')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.Secretaria')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('tipo_viatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.Tipo_viatico')),
            ],
        ),
        migrations.AddField(
            model_name='monto',
            name='Tipo_viatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.Tipo_viatico'),
        ),
    ]
