# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaticodiario',
            name='ncontrol',
            field=models.CharField(max_length=20),
        ),
    ]
