# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0003_auto_20190603_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaticodiario',
            options={'permissions': (('Centralizar', 'Ver Centralizador'), ('Reportes_Centralizar', 'Reportes Centralizador'), ('Reportes', 'Reportes'), ('Realizar_reportes_viaticos', 'Reportes Viaticos'), ('Realizar_reportes_servidor', 'Reportes Servidor Publico'), ('Busquedas', 'Busquedas'), ('Busquedas_viaticos', 'Busquedas Viaticos'), ('Busquedas_servidor', 'Busquedas Servidor Publico'))},
        ),
    ]
