# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0004_auto_20190603_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monto',
            options={'permissions': (('Ver_list_monto', 'Ver Monto'),)},
        ),
        migrations.AlterModelOptions(
            name='tipo_viatico',
            options={'permissions': (('Ver_list_tipo_viatico', 'Ver Tipo viatico'),)},
        ),
    ]
